[profile.default]
rpc_url = "${RPC_URL}"
src = "src"
out = "out"
libs = ["lib"]

[profile.env]
PRIVATE_KEY = "${PRIVATE_KEY}"
RPC_URL = "${RPC_URL}"

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options